// Генерирует out/sw.js с precache-списком всех ассетов статического экспорта.
// Запускается после `next build`. Относительные пути → корректны при любом basePath.
//
// Автообновление: имя кэша = хэш содержимого билда, поэтому каждый деплой —
// новый кэш; старые удаляются на activate. Навигации идут network-first
// (свежий HTML сразу после деплоя, кэш — офлайн-фолбэк), остальные ассеты —
// cache-first (в статическом экспорте они хэшированы и иммутабельны).
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const out = join(import.meta.dirname, '..', 'out');

function walk(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}

const files = walk(out)
  .map((f) => './' + relative(out, f).split(/[\\/]/).join('/'))
  .filter((f) => !f.endsWith('/sw.js') && f !== './sw.js')
  .filter((f) => !f.endsWith('.map'))
  .filter((f) => !f.endsWith('.DS_Store'))
  .sort();

const assets = new Set(files);
assets.add('./'); // навигация к корню (index.html)

const hash = createHash('sha256');
for (const f of files) {
  hash.update(f);
  hash.update(readFileSync(join(out, f)));
}
const version = hash.digest('hex').slice(0, 12);

const list = [...assets];

const sw = `// Auto-generated by scripts/gen-sw.mjs — do not edit.
const CACHE = 'uecon-pwa-${version}';
const ASSETS = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Навигации — network-first: после деплоя HTML свежий сразу, офлайн — из кэша.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() =>
          caches.match(req, { ignoreSearch: true }).then((cached) => cached || caches.match('./'))
        )
    );
    return;
  }

  // Остальные GET — cache-first: хэшированные ассеты статического экспорта иммутабельны.
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
        }
        return res;
      });
    })
  );
});
`;

writeFileSync(join(out, 'sw.js'), sw);
console.log(`sw.js generated: cache uecon-pwa-${version}, ${list.length} precached assets`);
