// Генерирует out/sw.js с precache-списком всех ассетов статического экспорта.
// Запускается после `next build`. Относительные пути → корректны при любом basePath.
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const out = join(import.meta.dirname, '..', 'out');

function walk(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}

const assets = new Set(
  walk(out)
    .map((f) => './' + relative(out, f).split(/[\\/]/).join('/'))
    .filter((f) => !f.endsWith('/sw.js') && f !== './sw.js')
    .filter((f) => !f.endsWith('.map'))
);
assets.add('./'); // навигация к корню (index.html)

const list = [...assets];

const sw = `// Auto-generated by scripts/gen-sw.mjs — do not edit.
const CACHE = 'uecon-pwa-v1';
const ASSETS = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => {
          if (req.mode === 'navigate') return caches.match('./');
          return undefined;
        });
    })
  );
});
`;

writeFileSync(join(out, 'sw.js'), sw);
console.log('sw.js generated with', list.length, 'precached assets');
